### ISSUE TITLE
InsertConfig and RegExp

### ISSUE THREAD

**Issue by Jezzuz** [SBoudrias/gruntfile-editor#31]
I am using grunt-wiredep in my yeoman scaffolding script to connect bower dependancies into my html files. I need to just slightly adjust the way wiredep handles this by passing its `fileTypes` option. 

```
html: {
      block: /(([ \t]*)<!--\s*bower:*(\S*)\s*-->)(\n|\r|.)*?(<!--\s*endbower\s*-->)/gi,
      detect: {
        js: /<script.*src=['"]([^'"]+)/gi,
        css: /<link.*href=['"]([^'"]+)/gi
      },
      replace: {
        js: '<script src="{{filePath}}"></script>',
        css: '<link rel="stylesheet" href="{{filePath}}" />'
      }
    },
``` 

Some attributes are set to raw RegExp. Just copying and pasting this, leaves me with the attributes being empty after yeoman ran. 

I already tried replacing raw regular expressions with `new RegExp("expression")`. Which didn't work. I guess wiredep doesn't take that.

Any idea on how I can let yeoman insert these regExps ?

**Comment by SBoudrias** [comment]
Is this an issue with Gruntfile Editor?

**Comment by Jezzuz** [comment]
grunt-editor's insertConfig can't handle regExp. That's the main point. I just tried to deliver some context.

**Comment by SBoudrias** [comment]
Can you provide a code example of what you're doing?

**Comment by Jezzuz** [comment]
Assembling your code example I just found out what the problem was: I had an error in my escapings on these RegExps. With correct escaping everything works as intended. 

Thanks for your help. Sorry for bothering you with that.
