### ISSUE TITLE
Anything similar for gulp ?

### ISSUE THREAD

**Issue by canercandan** [SBoudrias/gruntfile-editor#36]
Hey @SBoudrias,

Do you know a similar tool to edit a gulpfile.js ?

Thanks.

**Comment by SBoudrias** [comment]
Not at the moment.

Although coding it shouldn't be too hard. You could do like gruntfile-editor use AST-query to handle AST modification easily.

The main issue is that gulp files don't have a very define structure compared to Grunt. So it's kind of hard to really find useful and reusable patterns that would make such a tool work correctly.

**Comment by canercandan** [comment]
@SBoudrias thanks for your advice, I am using ast-query API for now and will see if something clean come out to publish a new reusable package as a gulp editor API.
