### ISSUE TITLE
#insertJavaScript(): Allow inserting raw JavaScript

### ISSUE THREAD

**Issue by eddiemonge** [SBoudrias/gruntfile-editor#9]
There should be a way to add custom requires (or variables, or even arbitrary code). One specific use case is Yeoman things like:

```
require('time-grunt')(grunt);
require('load-grunt-tasks')(grunt);
```

**Comment by snowball** [comment]
This would be very useful, currently having to avoid using the gruntfile editor approach in yeoman to because of this issue.
